// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: proto/helloworld/greeter.proto

package com_foo_service_helloworld

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//	*HelloRequest_Texter
	//	*HelloRequest_Number
	Value   isHelloRequest_Value `protobuf_oneof:"value"`
	TagList []*HelloRequestTag   `protobuf:"bytes,10,rep,name=tagList,proto3" json:"tagList,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_helloworld_greeter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_greeter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *HelloRequest) GetValue() isHelloRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *HelloRequest) GetTexter() string {
	if x, ok := x.GetValue().(*HelloRequest_Texter); ok {
		return x.Texter
	}
	return ""
}

func (x *HelloRequest) GetNumber() float64 {
	if x, ok := x.GetValue().(*HelloRequest_Number); ok {
		return x.Number
	}
	return 0
}

func (x *HelloRequest) GetTagList() []*HelloRequestTag {
	if x != nil {
		return x.TagList
	}
	return nil
}

type isHelloRequest_Value interface {
	isHelloRequest_Value()
}

type HelloRequest_Texter struct {
	Texter string `protobuf:"bytes,5,opt,name=texter,proto3,oneof"`
}

type HelloRequest_Number struct {
	Number float64 `protobuf:"fixed64,6,opt,name=number,proto3,oneof"`
}

func (*HelloRequest_Texter) isHelloRequest_Value() {}

func (*HelloRequest_Number) isHelloRequest_Value() {}

type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	TagResp  string `protobuf:"bytes,2,opt,name=tagResp,proto3" json:"tagResp,omitempty"`
	// Types that are assignable to Info:
	//	*HelloResponse_Info1
	//	*HelloResponse_Info2
	//	*HelloResponse_Info3
	Info isHelloResponse_Info `protobuf_oneof:"info"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_helloworld_greeter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_greeter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

func (x *HelloResponse) GetTagResp() string {
	if x != nil {
		return x.TagResp
	}
	return ""
}

func (m *HelloResponse) GetInfo() isHelloResponse_Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func (x *HelloResponse) GetInfo1() *Info1 {
	if x, ok := x.GetInfo().(*HelloResponse_Info1); ok {
		return x.Info1
	}
	return nil
}

func (x *HelloResponse) GetInfo2() *Info2 {
	if x, ok := x.GetInfo().(*HelloResponse_Info2); ok {
		return x.Info2
	}
	return nil
}

func (x *HelloResponse) GetInfo3() *Info3 {
	if x, ok := x.GetInfo().(*HelloResponse_Info3); ok {
		return x.Info3
	}
	return nil
}

type isHelloResponse_Info interface {
	isHelloResponse_Info()
}

type HelloResponse_Info1 struct {
	Info1 *Info1 `protobuf:"bytes,3,opt,name=info1,proto3,oneof"`
}

type HelloResponse_Info2 struct {
	Info2 *Info2 `protobuf:"bytes,4,opt,name=info2,proto3,oneof"`
}

type HelloResponse_Info3 struct {
	Info3 *Info3 `protobuf:"bytes,5,opt,name=info3,proto3,oneof"`
}

func (*HelloResponse_Info1) isHelloResponse_Info() {}

func (*HelloResponse_Info2) isHelloResponse_Info() {}

func (*HelloResponse_Info3) isHelloResponse_Info() {}

type Info1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbType string `protobuf:"bytes,1,opt,name=dbType,proto3" json:"dbType,omitempty"`
	//repeated tag tagList =2;
	//
	// Types that are assignable to ConnectType:
	//	*Info1_ConnectString
	//	*Info1_DsnNmae
	ConnectType isInfo1_ConnectType `protobuf_oneof:"connectType"`
}

func (x *Info1) Reset() {
	*x = Info1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_helloworld_greeter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info1) ProtoMessage() {}

func (x *Info1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_greeter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info1.ProtoReflect.Descriptor instead.
func (*Info1) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_greeter_proto_rawDescGZIP(), []int{2}
}

func (x *Info1) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (m *Info1) GetConnectType() isInfo1_ConnectType {
	if m != nil {
		return m.ConnectType
	}
	return nil
}

func (x *Info1) GetConnectString() string {
	if x, ok := x.GetConnectType().(*Info1_ConnectString); ok {
		return x.ConnectString
	}
	return ""
}

func (x *Info1) GetDsnNmae() string {
	if x, ok := x.GetConnectType().(*Info1_DsnNmae); ok {
		return x.DsnNmae
	}
	return ""
}

type isInfo1_ConnectType interface {
	isInfo1_ConnectType()
}

type Info1_ConnectString struct {
	ConnectString string `protobuf:"bytes,3,opt,name=connectString,proto3,oneof"`
}

type Info1_DsnNmae struct {
	DsnNmae string `protobuf:"bytes,4,opt,name=dsnNmae,proto3,oneof"`
}

func (*Info1_ConnectString) isInfo1_ConnectType() {}

func (*Info1_DsnNmae) isInfo1_ConnectType() {}

type Info2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbType string `protobuf:"bytes,1,opt,name=dbType,proto3" json:"dbType,omitempty"`
	//repeated tag tagList =2;
	//
	// Types that are assignable to ConnectType:
	//	*Info2_ConnectString
	//	*Info2_DsnNmae
	ConnectType isInfo2_ConnectType `protobuf_oneof:"connectType"`
}

func (x *Info2) Reset() {
	*x = Info2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_helloworld_greeter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info2) ProtoMessage() {}

func (x *Info2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_greeter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info2.ProtoReflect.Descriptor instead.
func (*Info2) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_greeter_proto_rawDescGZIP(), []int{3}
}

func (x *Info2) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (m *Info2) GetConnectType() isInfo2_ConnectType {
	if m != nil {
		return m.ConnectType
	}
	return nil
}

func (x *Info2) GetConnectString() string {
	if x, ok := x.GetConnectType().(*Info2_ConnectString); ok {
		return x.ConnectString
	}
	return ""
}

func (x *Info2) GetDsnNmae() string {
	if x, ok := x.GetConnectType().(*Info2_DsnNmae); ok {
		return x.DsnNmae
	}
	return ""
}

type isInfo2_ConnectType interface {
	isInfo2_ConnectType()
}

type Info2_ConnectString struct {
	ConnectString string `protobuf:"bytes,3,opt,name=connectString,proto3,oneof"`
}

type Info2_DsnNmae struct {
	DsnNmae string `protobuf:"bytes,4,opt,name=dsnNmae,proto3,oneof"`
}

func (*Info2_ConnectString) isInfo2_ConnectType() {}

func (*Info2_DsnNmae) isInfo2_ConnectType() {}

type Info3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbType string `protobuf:"bytes,1,opt,name=dbType,proto3" json:"dbType,omitempty"`
	//repeated tag tagList =2;
	//
	// Types that are assignable to ConnectType:
	//	*Info3_ConnectString
	//	*Info3_DsnNmae
	ConnectType isInfo3_ConnectType `protobuf_oneof:"connectType"`
}

func (x *Info3) Reset() {
	*x = Info3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_helloworld_greeter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info3) ProtoMessage() {}

func (x *Info3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_greeter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info3.ProtoReflect.Descriptor instead.
func (*Info3) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_greeter_proto_rawDescGZIP(), []int{4}
}

func (x *Info3) GetDbType() string {
	if x != nil {
		return x.DbType
	}
	return ""
}

func (m *Info3) GetConnectType() isInfo3_ConnectType {
	if m != nil {
		return m.ConnectType
	}
	return nil
}

func (x *Info3) GetConnectString() string {
	if x, ok := x.GetConnectType().(*Info3_ConnectString); ok {
		return x.ConnectString
	}
	return ""
}

func (x *Info3) GetDsnNmae() string {
	if x, ok := x.GetConnectType().(*Info3_DsnNmae); ok {
		return x.DsnNmae
	}
	return ""
}

type isInfo3_ConnectType interface {
	isInfo3_ConnectType()
}

type Info3_ConnectString struct {
	ConnectString string `protobuf:"bytes,3,opt,name=connectString,proto3,oneof"`
}

type Info3_DsnNmae struct {
	DsnNmae string `protobuf:"bytes,4,opt,name=dsnNmae,proto3,oneof"`
}

func (*Info3_ConnectString) isInfo3_ConnectType() {}

func (*Info3_DsnNmae) isInfo3_ConnectType() {}

type HelloRequestTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName  string `protobuf:"bytes,6,opt,name=tableName,proto3" json:"tableName,omitempty"`
	TagName    string `protobuf:"bytes,7,opt,name=tagName,proto3" json:"tagName,omitempty"`
	ColumnName string `protobuf:"bytes,8,opt,name=columnName,proto3" json:"columnName,omitempty"`
	TagType    string `protobuf:"bytes,9,opt,name=tagType,proto3" json:"tagType,omitempty"`
}

func (x *HelloRequestTag) Reset() {
	*x = HelloRequestTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_helloworld_greeter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequestTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequestTag) ProtoMessage() {}

func (x *HelloRequestTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_greeter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequestTag.ProtoReflect.Descriptor instead.
func (*HelloRequestTag) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_greeter_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HelloRequestTag) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *HelloRequestTag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *HelloRequestTag) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *HelloRequestTag) GetTagType() string {
	if x != nil {
		return x.TagType
	}
	return ""
}

var File_proto_helloworld_greeter_proto protoreflect.FileDescriptor

var file_proto_helloworld_greeter_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0xa0, 0x02, 0x0a,
	0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x06, 0x74, 0x65, 0x78, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x74, 0x65, 0x78, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x74, 0x61, 0x67, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x77, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0xfe, 0x01, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x31,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x31, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x66,
	0x6f, 0x31, 0x12, 0x39, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x49,
	0x6e, 0x66, 0x6f, 0x32, 0x48, 0x00, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x32, 0x12, 0x39, 0x0a,
	0x05, 0x69, 0x6e, 0x66, 0x6f, 0x33, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x33, 0x48,
	0x00, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x33, 0x42, 0x06, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x22, 0x72, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x31, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x62, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x62, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x26, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x07, 0x64, 0x73, 0x6e,
	0x4e, 0x6d, 0x61, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x64, 0x73,
	0x6e, 0x4e, 0x6d, 0x61, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x22, 0x72, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x62, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a,
	0x07, 0x64, 0x73, 0x6e, 0x4e, 0x6d, 0x61, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x07, 0x64, 0x73, 0x6e, 0x4e, 0x6d, 0x61, 0x65, 0x42, 0x0d, 0x0a, 0x0b, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x72, 0x0a, 0x05, 0x49, 0x6e, 0x66, 0x6f,
	0x33, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x62, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x0d, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x12, 0x1a, 0x0a, 0x07, 0x64, 0x73, 0x6e, 0x4e, 0x6d, 0x61, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x64, 0x73, 0x6e, 0x4e, 0x6d, 0x61, 0x65, 0x42, 0x0d, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x32, 0xcd, 0x01, 0x0a,
	0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x5e, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x12, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x09, 0x4e, 0x65, 0x78, 0x74,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_helloworld_greeter_proto_rawDescOnce sync.Once
	file_proto_helloworld_greeter_proto_rawDescData = file_proto_helloworld_greeter_proto_rawDesc
)

func file_proto_helloworld_greeter_proto_rawDescGZIP() []byte {
	file_proto_helloworld_greeter_proto_rawDescOnce.Do(func() {
		file_proto_helloworld_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_helloworld_greeter_proto_rawDescData)
	})
	return file_proto_helloworld_greeter_proto_rawDescData
}

var file_proto_helloworld_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_helloworld_greeter_proto_goTypes = []interface{}{
	(*HelloRequest)(nil),    // 0: com.foo.service.helloworld.HelloRequest
	(*HelloResponse)(nil),   // 1: com.foo.service.helloworld.HelloResponse
	(*Info1)(nil),           // 2: com.foo.service.helloworld.Info1
	(*Info2)(nil),           // 3: com.foo.service.helloworld.Info2
	(*Info3)(nil),           // 4: com.foo.service.helloworld.Info3
	(*HelloRequestTag)(nil), // 5: com.foo.service.helloworld.HelloRequest.tag
}
var file_proto_helloworld_greeter_proto_depIdxs = []int32{
	5, // 0: com.foo.service.helloworld.HelloRequest.tagList:type_name -> com.foo.service.helloworld.HelloRequest.tag
	2, // 1: com.foo.service.helloworld.HelloResponse.info1:type_name -> com.foo.service.helloworld.Info1
	3, // 2: com.foo.service.helloworld.HelloResponse.info2:type_name -> com.foo.service.helloworld.Info2
	4, // 3: com.foo.service.helloworld.HelloResponse.info3:type_name -> com.foo.service.helloworld.Info3
	0, // 4: com.foo.service.helloworld.Greeter.Hello:input_type -> com.foo.service.helloworld.HelloRequest
	0, // 5: com.foo.service.helloworld.Greeter.NextHello:input_type -> com.foo.service.helloworld.HelloRequest
	1, // 6: com.foo.service.helloworld.Greeter.Hello:output_type -> com.foo.service.helloworld.HelloResponse
	1, // 7: com.foo.service.helloworld.Greeter.NextHello:output_type -> com.foo.service.helloworld.HelloResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_helloworld_greeter_proto_init() }
func file_proto_helloworld_greeter_proto_init() {
	if File_proto_helloworld_greeter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_helloworld_greeter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_helloworld_greeter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_helloworld_greeter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_helloworld_greeter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_helloworld_greeter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_helloworld_greeter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequestTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_helloworld_greeter_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*HelloRequest_Texter)(nil),
		(*HelloRequest_Number)(nil),
	}
	file_proto_helloworld_greeter_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*HelloResponse_Info1)(nil),
		(*HelloResponse_Info2)(nil),
		(*HelloResponse_Info3)(nil),
	}
	file_proto_helloworld_greeter_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Info1_ConnectString)(nil),
		(*Info1_DsnNmae)(nil),
	}
	file_proto_helloworld_greeter_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Info2_ConnectString)(nil),
		(*Info2_DsnNmae)(nil),
	}
	file_proto_helloworld_greeter_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*Info3_ConnectString)(nil),
		(*Info3_DsnNmae)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_helloworld_greeter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_helloworld_greeter_proto_goTypes,
		DependencyIndexes: file_proto_helloworld_greeter_proto_depIdxs,
		MessageInfos:      file_proto_helloworld_greeter_proto_msgTypes,
	}.Build()
	File_proto_helloworld_greeter_proto = out.File
	file_proto_helloworld_greeter_proto_rawDesc = nil
	file_proto_helloworld_greeter_proto_goTypes = nil
	file_proto_helloworld_greeter_proto_depIdxs = nil
}
