// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: proto/helloworld/greeter.proto

package com_foo_service_helloworld

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//	*HelloRequest_Texter
	//	*HelloRequest_Number
	Value   isHelloRequest_Value `protobuf_oneof:"value"`
	TagList []*HelloRequestTag   `protobuf:"bytes,10,rep,name=tagList,proto3" json:"tagList,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_helloworld_greeter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_greeter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *HelloRequest) GetValue() isHelloRequest_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *HelloRequest) GetTexter() string {
	if x, ok := x.GetValue().(*HelloRequest_Texter); ok {
		return x.Texter
	}
	return ""
}

func (x *HelloRequest) GetNumber() float64 {
	if x, ok := x.GetValue().(*HelloRequest_Number); ok {
		return x.Number
	}
	return 0
}

func (x *HelloRequest) GetTagList() []*HelloRequestTag {
	if x != nil {
		return x.TagList
	}
	return nil
}

type isHelloRequest_Value interface {
	isHelloRequest_Value()
}

type HelloRequest_Texter struct {
	Texter string `protobuf:"bytes,5,opt,name=texter,proto3,oneof"`
}

type HelloRequest_Number struct {
	Number float64 `protobuf:"fixed64,6,opt,name=number,proto3,oneof"`
}

func (*HelloRequest_Texter) isHelloRequest_Value() {}

func (*HelloRequest_Number) isHelloRequest_Value() {}

type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Greeting string `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	TagResp  string `protobuf:"bytes,2,opt,name=tagResp,proto3" json:"tagResp,omitempty"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_helloworld_greeter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_greeter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

func (x *HelloResponse) GetTagResp() string {
	if x != nil {
		return x.TagResp
	}
	return ""
}

type HelloRequestTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName  string `protobuf:"bytes,6,opt,name=tableName,proto3" json:"tableName,omitempty"`
	TagName    string `protobuf:"bytes,7,opt,name=tagName,proto3" json:"tagName,omitempty"`
	ColumnName string `protobuf:"bytes,8,opt,name=columnName,proto3" json:"columnName,omitempty"`
	TagType    string `protobuf:"bytes,9,opt,name=tagType,proto3" json:"tagType,omitempty"`
}

func (x *HelloRequestTag) Reset() {
	*x = HelloRequestTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_helloworld_greeter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequestTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequestTag) ProtoMessage() {}

func (x *HelloRequestTag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_helloworld_greeter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequestTag.ProtoReflect.Descriptor instead.
func (*HelloRequestTag) Descriptor() ([]byte, []int) {
	return file_proto_helloworld_greeter_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HelloRequestTag) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *HelloRequestTag) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *HelloRequestTag) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *HelloRequestTag) GetTagType() string {
	if x != nil {
		return x.TagType
	}
	return ""
}

var File_proto_helloworld_greeter_proto protoreflect.FileDescriptor

var file_proto_helloworld_greeter_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1a, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x22, 0xa0, 0x02, 0x0a,
	0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x06, 0x74, 0x65, 0x78, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x06, 0x74, 0x65, 0x78, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74,
	0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f,
	0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x74, 0x61, 0x67, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x77, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x61, 0x67, 0x54, 0x79, 0x70, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x45, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x74, 0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x61, 0x67, 0x52, 0x65, 0x73, 0x70, 0x32, 0xcd, 0x01, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74,
	0x65, 0x72, 0x12, 0x5e, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x28, 0x2e, 0x63, 0x6f,
	0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x62, 0x0a, 0x09, 0x4e, 0x65, 0x78, 0x74, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12,
	0x28, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c,
	0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x63, 0x6f, 0x6d, 0x2e,
	0x66, 0x6f, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_helloworld_greeter_proto_rawDescOnce sync.Once
	file_proto_helloworld_greeter_proto_rawDescData = file_proto_helloworld_greeter_proto_rawDesc
)

func file_proto_helloworld_greeter_proto_rawDescGZIP() []byte {
	file_proto_helloworld_greeter_proto_rawDescOnce.Do(func() {
		file_proto_helloworld_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_helloworld_greeter_proto_rawDescData)
	})
	return file_proto_helloworld_greeter_proto_rawDescData
}

var file_proto_helloworld_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_helloworld_greeter_proto_goTypes = []interface{}{
	(*HelloRequest)(nil),    // 0: com.foo.service.helloworld.HelloRequest
	(*HelloResponse)(nil),   // 1: com.foo.service.helloworld.HelloResponse
	(*HelloRequestTag)(nil), // 2: com.foo.service.helloworld.HelloRequest.tag
}
var file_proto_helloworld_greeter_proto_depIdxs = []int32{
	2, // 0: com.foo.service.helloworld.HelloRequest.tagList:type_name -> com.foo.service.helloworld.HelloRequest.tag
	0, // 1: com.foo.service.helloworld.Greeter.Hello:input_type -> com.foo.service.helloworld.HelloRequest
	0, // 2: com.foo.service.helloworld.Greeter.NextHello:input_type -> com.foo.service.helloworld.HelloRequest
	1, // 3: com.foo.service.helloworld.Greeter.Hello:output_type -> com.foo.service.helloworld.HelloResponse
	1, // 4: com.foo.service.helloworld.Greeter.NextHello:output_type -> com.foo.service.helloworld.HelloResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_helloworld_greeter_proto_init() }
func file_proto_helloworld_greeter_proto_init() {
	if File_proto_helloworld_greeter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_helloworld_greeter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_helloworld_greeter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_helloworld_greeter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequestTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_helloworld_greeter_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*HelloRequest_Texter)(nil),
		(*HelloRequest_Number)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_helloworld_greeter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_helloworld_greeter_proto_goTypes,
		DependencyIndexes: file_proto_helloworld_greeter_proto_depIdxs,
		MessageInfos:      file_proto_helloworld_greeter_proto_msgTypes,
	}.Build()
	File_proto_helloworld_greeter_proto = out.File
	file_proto_helloworld_greeter_proto_rawDesc = nil
	file_proto_helloworld_greeter_proto_goTypes = nil
	file_proto_helloworld_greeter_proto_depIdxs = nil
}
