// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: nextHello/proto/nextHelloWorld/nextGreeter.proto

package com_foo_service_nexthelloworld

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for NextGreeter service

func NewNextGreeterEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for NextGreeter service

type NextGreeterService interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error)
}

type nextGreeterService struct {
	c    client.Client
	name string
}

func NewNextGreeterService(name string, c client.Client) NextGreeterService {
	return &nextGreeterService{
		c:    c,
		name: name,
	}
}

func (c *nextGreeterService) Hello(ctx context.Context, in *HelloRequest, opts ...client.CallOption) (*HelloResponse, error) {
	req := c.c.NewRequest(c.name, "NextGreeter.Hello", in)
	out := new(HelloResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NextGreeter service

type NextGreeterHandler interface {
	Hello(context.Context, *HelloRequest, *HelloResponse) error
}

func RegisterNextGreeterHandler(s server.Server, hdlr NextGreeterHandler, opts ...server.HandlerOption) error {
	type nextGreeter interface {
		Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error
	}
	type NextGreeter struct {
		nextGreeter
	}
	h := &nextGreeterHandler{hdlr}
	return s.Handle(s.NewHandler(&NextGreeter{h}, opts...))
}

type nextGreeterHandler struct {
	NextGreeterHandler
}

func (h *nextGreeterHandler) Hello(ctx context.Context, in *HelloRequest, out *HelloResponse) error {
	return h.NextGreeterHandler.Hello(ctx, in, out)
}
